name: 'Pull Request Notification'
on:
  pull_request:
    types: [opened]    

jobs:
  notify-opened:
    runs-on: ubuntu-latest
    steps:
      - name: Notify to Typetalk
        uses: shomatan/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 288578
          message: "A pull request is opened at hydralibs: ${{ github.event.pull_request.title }}\n${{ github.event.repository.url }}/pull/${{ github.event.pull_request.id }}"
